let a = 4;
let b = 3;


console.log("a + b is " , a +b);
console.log("a + b is " , a +b);
console.log("a + b is " , a +b);
console.log("a + b is " , a +b);


// console.log("a + b is " , a +c); it'll throw error 
try{
    console.log("a + b is " , a +b);
} catch(err)
{
    console.log(err);
}


console.log("executing after error !! Life's good");
